kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world1
run:
  image: appleboy/drone-ssh
    host: 172.17.0.1
    port: 22
    username: wangjie
    password: wangjie8217
    script:
      - cd /home/wangjie/app/ok-project
      - ./repull.sh