kind: pipeline
name: ok应用自动部署

steps:
#  - name: 规范检测
#    image: golang
#    environment:
#      GO111MODULE: on
#      GOPROXY: https://goproxy.cn
#    commands:
#      - go get github.com/golangci/golangci-lint/cmd/golangci-lint
#      - golangci-lint run
#  - name: 单元测试
#    image: golang
#    pull: never
#    commands:
#      - GOPROXY=https://goproxy.cn go build
#      - go test ./...
#  - name: 构建镜像
#    image: plugins/docker
#    pull: never
#    settings:
#      mirror: https://qcxmbvw.mirror.aliyuncs.com
#      registry: registry.cn-hangzhou.aliyuncs.com
#      repo: registry.cn-hangzhou.aliyuncs.com/wangjie_dev/ok-project
#      use_cache: true
#      username: 13373381619
#      password: wangjie8217
#    tags:
#      - latest
#    when:
#      event: push
#      branch: master
#  - name: 部署镜像
#    image: appleboy/drone-ssh
#    pull: never
#    settings:
#      host: '172.17.0.1'
#      username: 'wangjie'
#      password: 'wangjie8217'
#      port: 22
#      script:
#        - docker pull registry.cn-hangzhou.aliyuncs.com/wangjie_dev/ok-project
#        - docker stop ok-project && docker stop ok-project-stand && docker rm $(docker ps -a | grep ok-project | awk '{print $1}'| tr '\n' ' ')
#        - docker create --name ok-project -v /home/wangjie/app/ok-project/etc/config.yaml:/etc/ok_project/config.yaml --network app-network --network-alias app-node1 registry.cn-hangzhou.aliyuncs.com/wangjie_dev/ok-project:latest
#        - docker start ok-project
#        - docker create --name ok-project-stand -v /home/wangjie/app/ok-project/etc/config.yaml:/etc/ok_project/config.yaml --network app-network --network-alias app-node2 registry.cn-hangzhou.aliyuncs.com/wangjie_dev/ok-project:latest
#        - docker start ok-project-stand
#        - echo 部署完成
  - name: 钉钉通知结果
    image: lddsb/drone-dingtalk-message
    pull: never
    settings:
      debug: true
      tips_title: 再试试
#      message_color: 00800
      type: markdown
      token: 63443d92f7023155a29e068136dd26bfaff2fe7458213a0a772f02988ba41c01
      secret: SECd34fc7b5b3589587484a7ba0c07068b3b0b24835c6b695127e08ef2daeeea20d
      success_pic: https://camo.githubusercontent.com/6002730968e34dc35d3050284ca79805e226e0cb6161cdb3cdee34a00f0f00f6/68747470733a2f2f692e696d6775722e636f6d2f78467243545a702e6a7067
#      tpl: "[PLUGIN_SUCCESS_PIC]"
#      message_color: true
#      message_pic: true
#      sha_link: true
#      success_pic: "https://camo.githubusercontent.com/6002730968e34dc35d3050284ca79805e226e0cb6161cdb3cdee34a00f0f00f6/68747470733a2f2f692e696d6775722e636f6d2f78467243545a702e6a7067"
#      failure_pic: true
      debug: true