kind: pipeline
name: ok应用自动部署

steps:
  - name: linter
    image: golang:latest
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - golangci-lint run
  - name: 构建镜像
    image: plugins/docker
    settings:
      repo: localhost:5000
      use_cache: true
#      username:
#        from_secret: docker_username
#      password:
#        from_secret: docker_password
    tags:
      - latest
    when:
      event: push
      branch: master
  - name: 执行单元测试
    image: golang
    pull: never
    commands:
      - GOPROXY=https://goproxy.cn go build
      - go test ./...
  - name: 构建
    image: alpine
    pull: never
    commands:
      - echo hello
      - echo world
  - name: 部署
    image: appleboy/drone-ssh
    pull: never
    settings:
      host: '172.17.0.1'
      username: 'wangjie'
      password: 'wangjie8217'
      port: 22
      script:
        - /home/wangjie/app/ok-project/repull.sh