kind: pipeline
name: 打包测试

steps:
  - name: 构建
  - name: 部署
    image: appleboy/drone-ssh
    settings:
      host: '172.17.0.1'
      username: 'wangjie'
      password: 'wangjie8217'
      port: 22
      script:
        - - echo ====开始部署=======
        - /home/wangjie/app/ok-project/repull.sh
        - echo ====部署成功======